services:
  docker-monitor:
    build: .

    container_name: docker-monitor

    ports:
      - "3000:3000"

    environment:
      - HOST_HOSTNAME=${HOSTNAME}

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    restart: unless-stopped